--------------------------------------------------------
--  DDL for Table GAME_CREDITCARD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GAME_CREDITCARD" 
   (	"CARD_NUMBER" NUMBER, 
	"CVC" NUMBER, 
	"US_NAME" VARCHAR2(20 BYTE), 
	"EX_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
