--------------------------------------------------------
--  DDL for Table GAME_COMPANY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GAME_COMPANY" 
   (	"COM_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"COUNTRY" VARCHAR2(20 BYTE), 
	"WEB" VARCHAR2(50 BYTE), 
	"COM_ID" NUMBER, 
	"OFI_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
