--------------------------------------------------------
--  Constraints for Table GAME_OFF
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GAME_OFF" ADD CONSTRAINT "GAME_OFF_PK" PRIMARY KEY ("OF_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GAME_OFF" MODIFY ("OF_LNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_OFF" MODIFY ("OF_FNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_OFF" MODIFY ("OF_PASS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_OFF" MODIFY ("OF_ID" NOT NULL ENABLE);
