--------------------------------------------------------
--  Constraints for Table GAMES
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GAMES" ADD CONSTRAINT "GAMES_PK" PRIMARY KEY ("GAMES_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("GCOM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("GCOMPANY" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("GAMENAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAMES" MODIFY ("GAMES_ID" NOT NULL ENABLE);
