--------------------------------------------------------
--  Constraints for Table GAME_COMPANY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GAME_COMPANY" ADD CONSTRAINT "GAME_COMPANY_PK" PRIMARY KEY ("COM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GAME_COMPANY" MODIFY ("OFI_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_COMPANY" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_COMPANY" MODIFY ("COM_ID" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_COMPANY" MODIFY ("COM_NAME" NOT NULL ENABLE);
