--------------------------------------------------------
--  DDL for Table GAME_OFF
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."GAME_OFF" 
   (	"OF_ID" NUMBER, 
	"OF_PASS" VARCHAR2(20 BYTE), 
	"OF_FNAME" VARCHAR2(20 BYTE), 
	"OF_LNAME" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
