--------------------------------------------------------
--  Constraints for Table GAME_USER
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."GAME_USER" ADD CONSTRAINT "GAME_USER_PK" PRIMARY KEY ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."GAME_USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_USER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."GAME_USER" MODIFY ("CARD_NUMBER" NOT NULL ENABLE);
